services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana

    environment:
      # --- Basic admin setup ---
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

      # --- Enable anonymous access (required for public dashboards) ---
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

      # --- Enable public dashboards feature toggle ---
      - GF_FEATURE_TOGGLES_publicDashboards=true
